name: Deploy to Github Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.201'
    
    - name: Build Application
      run: dotnet publish -c Release ./Server/Fullstack.Server.csproj

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
           github_token: 44c7fac6ca9cb479fc733cd07aa6e4e4cbc43209
           publish_dir: ./Server/bin/Release/netcoreapp3.1/publish/wwwroot/